plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'network.tamga'
version = '0.1.0'

android {
  namespace "network.tamga.keys"
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  // Play Integrity (cihaz kanıtı, ARF WIAM_04/08) — 2. adım
  implementation "com.google.android.play:integrity:1.4.0"
}
