// ADR-0032 Aşama 3 — Longfellow ZK doğrulayıcısını WebAssembly'e derler ve paketteki kopyayı günceller.
//   npm run zk:build            (packages/verifier kökünden; Rust + wasm32-unknown-unknown hedefi gerekir)
//   npm run zk:build -- --check (derler, paketteki .wasm ile bayt bayt aynı mı denetler; değiştirmez)
//
// Kaynak: packages/verifier/zk (Cargo.toml `rev` = upstream longfellow-zk sabit commit). C bağımlılığı `zstd` saf Rust ara
// katmanla yamalıdır (zk/zstd-shim), bu yüzden C derleyicisi gerekmez. Çıktı depoya girer; paketi kullananlar Rust gerektirmez.
// Devre dosyaları (src/zk/circuits/<circuit_id>.zst) doğrulayıcı derlemesinden bağımsızdır: Longfellow devre üreticisi
// (experiments/zk-longfellow `tamga-zk circuit`) belirlenimci üretir; özetleri imzalı güven listesinde (`lotl.zk_circuits`).
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CRATE = join(PKG, "zk");
const OUT = join(PKG, "src", "zk");
const TARGET_DIR = process.env.CARGO_TARGET_DIR ?? join(homedir(), "tools", "tz-wasm-target");
const check = process.argv.includes("--check");

const cargoBin = join(homedir(), ".cargo", "bin");
const env = {
  ...process.env,
  // Yalnız Rust'ın kendi bağlayıcısı: ana makine derleme betikleri için dış gcc gerekmez (PATH'teki gcc'yi dışarıda tut).
  PATH: [
    cargoBin,
    ...(process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":").filter((p) => !/w64devkit/i.test(p)),
  ].join(process.platform === "win32" ? ";" : ":"),
  CARGO_TARGET_DIR: TARGET_DIR,
  // Derleyen makinenin yolları (kullanıcı adı dahil) wasm'a gömülmez: hata konumu dizgeleri nötr önekle yazılır. Yollarda boşluk
  // olabildiği için RUSTFLAGS yerine \x1f ayraçlı CARGO_ENCODED_RUSTFLAGS. Çıktı makineden bağımsız → --check her makinede tutar.
  CARGO_ENCODED_RUSTFLAGS: [
    "--cfg",
    'getrandom_backend="custom"',
    `--remap-path-prefix=${process.env.CARGO_HOME ?? join(homedir(), ".cargo")}=/cargo`,
    `--remap-path-prefix=${process.env.RUSTUP_HOME ?? join(homedir(), ".rustup")}=/rustup`,
    `--remap-path-prefix=${CRATE}=/crate`,
    `--remap-path-prefix=${homedir()}=/home`,
  ].join("\x1f"),
};
execFileSync("cargo", ["build", "--release", "--locked", "--target", "wasm32-unknown-unknown"], {
  cwd: CRATE,
  env,
  stdio: "inherit",
});
const built = join(TARGET_DIR, "wasm32-unknown-unknown", "release", "tamga_zk_verifier.wasm");
const sha = (p) => createHash("sha256").update(readFileSync(p)).digest("hex");
const dest = join(OUT, "longfellow-verifier.wasm");
if (check) {
  if (!existsSync(dest) || sha(dest) !== sha(built)) {
    console.error(
      `zk:build --check: paketteki wasm derlemeyle aynı değil (${existsSync(dest) ? sha(dest) : "yok"} ≠ ${sha(built)})`,
    );
    process.exit(1);
  }
  console.log(`zk:build --check: aynı (${sha(built)})`);
  process.exit(0);
}
copyFileSync(built, dest);
const cargo = readFileSync(join(CRATE, "Cargo.toml"), "utf8");
const rev = /rev = "([0-9a-f]{40})"/.exec(cargo)?.[1];
const circuits = Object.fromEntries(
  readdirSync(join(OUT, "circuits"))
    .filter((f) => f.endsWith(".zst"))
    .map((f) => [f.replace(/\.zst$/, ""), sha(join(OUT, "circuits", f))]),
);
const manifest = {
  note: "ADR-0032: Longfellow ZK mdoc verifier (WASM) and trusted circuit files. Generated by scripts/zk-build.mjs.",
  system: "longfellow-libzk-v1",
  upstream: { repo: "https://github.com/longfellow-zk/longfellow-zk", rev },
  wasm: { file: "longfellow-verifier.wasm", sha256: sha(dest), bytes: readFileSync(dest).length },
  circuits,
};
writeFileSync(join(OUT, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
console.log(`zk:build: ${manifest.wasm.bytes} B, sha256 ${manifest.wasm.sha256}`);
